export const initialFormData = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  password: "",
  address: "",
  gender: "",
  dateOfBirth: "",
  hiredDate: "",
  position: "",
  status: "",
  ratePerHour: "",
  shift: "",
  role: "",
};
